<?php

namespace module\ClientWebsitePortalBundle\Entity;
use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\DriverManager;
use module\QuestionnaireBundle\Entity\Response;
use Symfony\Component\Config\Definition\Exception\Exception;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface {
	public function loadUserByUsername($username) {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
